version: "3.8"

services:
  backend:
    build:
      context: ../backend
    container_name: systemkadeh_backend_dev
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env.dev
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthz/" ]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:16.3-alpine
    container_name: systemkadeh_postgres_dev
    restart: always
    env_file:
      - ../.env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
