version: "3.8"

services:
  backend:
    build:
      context: ../backend
    container_name: systemkadeh_backend_dev
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env.dev
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15
    container_name: systemkadeh_postgres_dev
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
