version: "3.8"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: systemkadeh_backend_prod
    env_file:
      - ../.env.prod
    volumes:
      - static_volume:/app/static
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: systemkadeh_postgres_prod
    restart: always
    env_file:
      - ../.env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: systemkadeh_nginx_prod
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data_prod:
  static_volume:
